<?php
/**
 * Projects Data
 */

// Include project status management
require_once __DIR__ . '/project-status.php';

$projects = [
    'makkah-duct-work' => [
        'title' => 'Makkah Project - Duct Work',
        'title_ar' => 'مشروع مكة - أعمال القنوات',
        'category' => 'MEP',
        'status' => 'on-hold',
        'location' => 'Makkah',
        'contract_value' => '6 MM SAR',
        'scope' => 'Duct work installation and MEP services',
        'description' => 'Professional duct work installation for Makkah project, ensuring optimal air distribution and ventilation systems.',
        'description_ar' => 'تركيب احترافي لأعمال القنوات لمشروع مكة، يضمن توزيع الهواء الأمثل وأنظمة التهوية.',
        'specs' => [
            'Scope of Work' => 'Duct Work',
            'Contract Value' => '6 Million SAR',
            'Location' => 'Makkah',
            'Status' => 'Completed',
        ],
        'contract_pdf' => 'makkah-duct-work-2026-04-02_08-01-29-contract.pdf',
        'visible' => '1',
    ],
    'makkah-electrical' => [
        'title' => 'Makkah Project - Electrical Work',
        'title_ar' => 'مشروع مكة - أعمال كهربائية',
        'category' => 'MEP',
        'status' => 'in-progress',
        'location' => 'Makkah',
        'contract_value' => '3.2 MM SAR',
        'scope' => 'Electrical work installation and services',
        'description' => 'Complete electrical systems installation for Makkah project, including power distribution, lighting, and control systems.',
        'description_ar' => 'تركيب أنظمة كهربائية كاملة لمشروع مكة، بما في ذلك توزيع الطاقة، والإضاءة، وأنظمة التحكم.',
        'specs' => [
            'Scope of Work' => 'Electrical Work',
            'Contract Value' => '3.2 Million SAR',
            'Location' => 'Makkah',
            'Status' => 'Completed',
        ],
        'visible' => '1',
        'contract_pdf' => 'makkah-electrical-2026-04-05_13-51-21-contract.pdf',
    ],
    'rimal-project' => [
        'title' => 'Rimal Project',
        'title_ar' => 'مشروع ريمال',
        'category' => 'Infrastructure',
        'status' => 'planning',
        'location' => 'Riyadh',
        'contract_value' => '11 MM SAR',
        'scope' => 'Civil, Mechanical, and Electrical work',
        'description' => 'Comprehensive civil, mechanical, and electrical work for Rimal project, delivering integrated construction solutions.',
        'description_ar' => 'أعمال مدنية وميكانيكية وكهربائية شاملة لمشروع ريمال، وتقديم حلول بناء متكاملة.',
        'specs' => [
            'Scope of Work' => 'Civil – Mechanical- Electrical',
            'Contract Value' => '11 Million SAR',
            'Location' => 'Riyadh',
            'Status' => 'Completed',
        ],
        'visible' => '1',
    ],
    'exit-9-project' => [
        'title' => 'Exit 9 Project',
        'title_ar' => 'مشروع المخرج ٩',
        'category' => 'Infrastructure',
        'status' => 'completed',
        'location' => 'Riyadh',
        'contract_value' => 'N/A',
        'scope' => 'Civil, Mechanical, and Electrical work',
        'description' => 'Infrastructure development project at Exit 9, including comprehensive civil, mechanical, and electrical systems.',
        'description_ar' => 'مشروع تطوير البنية التحتية عند المخرج ٩، بما في ذلك أنظمة مدنية وميكانيكية وكهربائية شاملة.',
        'specs' => [
            'Scope of Work' => 'Civil – Mechanical- Electrical',
            'Location' => 'Riyadh',
            'Status' => 'Completed',
        ],
        'visible' => '1',
    ],
    'lamar-towers' => [
        'title' => 'Lamar Towers Project',
        'title_ar' => 'مشروع أبراج لامار',
        'category' => 'MEP',
        'status' => 'completed',
        'location' => 'Corniche Road, Jeddah',
        'contract_value' => 'N/A',
        'scope' => 'RCC & MEP, With TAROUK CONTRACTING COMPANY',
        'description' => 'Two towers from 13th floor till 37th floor covering 60,000m² plus podium 10,000 m². A landmark project in Jeddah showcasing DIAR 360\'s expertise in high-rise construction.',
        'description_ar' => 'برجين من الطابق ١٣ حتى الطابق ٣٧ تغطية مساحة ٦٠,٠٠٠ م² بالإضافة إلى منصة مساحتها ١٠,٠٠٠ م². مشروع معلم بارز في جدة يعرض خبرة ديار ٣٦٠ في بناء ناطات مرتفعة.',
        'specs' => [
            'Project Area' => '2 Towers: 60,000 m² + Podium: 10,000 m²',
            'Floors' => '2 Towers from 13th to 37th floor',
            'Location' => 'Corniche Road, Jeddah',
            'Partner' => 'TAROUK CONTRACTING COMPANY',
            'Status' => 'Completed',
        ],
        'visible' => '1',
    ],
    'elegance-tower' => [
        'title' => 'Elegance Tower Project',
        'title_ar' => 'مشروع برج إيلجانس',
        'category' => 'Industrial',
        'status' => 'completed',
        'location' => 'Riyadh',
        'contract_value' => 'N/A',
        'scope' => 'RCC & MEP, With TAROUK CONTRACTING COMPANY',
        'description' => '28 floors covering 28,000 m² and 5 basements totaling 35,000 m². A prestigious tower project in Riyadh demonstrating excellence in structural and MEP engineering.',
        'description_ar' => '٢٨ طوابق تغطي ٢٨,٠٠٠ م² و٥ طوابق سردية بإجمالي ٣٥,٠٠٠ م². مشروع برج مشهور في الرياض يظهر التميز في الهندسة الإنشائية والهندسة.',
        'specs' => [
            'Project Area' => '28 Floors: 28,000 m² + 5 Basements: 35,000 m²',
            'Total Area' => '63,000 m²',
            'Location' => 'Riyadh',
            'Partner' => 'TAROUK CONTRACTING COMPANY',
            'Status' => 'Completed',
        ],
        'visible' => '1',
    ],
    'ramla-tower' => [
        'title' => 'Ramla Tower Project',
        'title_ar' => 'مشروع برج رملة',
        'category' => 'Commercial',
        'status' => 'completed',
        'location' => 'Riyadh',
        'contract_value' => 'N/A',
        'scope' => 'RCC & MEP with FIRST COMPANY',
        'description' => '40 floors and 2 basements covering 63,000 m² plus 10,000 m³ foundation. A major high-rise development showcasing advanced construction techniques.',
        'description_ar' => '٤٠ طوابق و٢ طوابق سردية تغطي مساحة ٦٣,٠٠٠ م² بالإضافة إلى ١٠,٠٠٠ م³ أساس. مشروع مرتفع رئيسي يعرض تقنيات بناء متقدمة.',
        'specs' => [
            'Project Area' => '40 floors and 2 basements: 63,000 m²',
            'Foundation' => '10,000 m³',
            'Location' => 'Riyadh',
            'Partner' => 'FIRST COMPANY',
            'Status' => 'Completed',
        ],
        'visible' => '1',
    ],
    '309-310-tower-kafd' => [
        'title' => '309,310 Tower Project (KAFD)',
        'title_ar' => 'مشروع برج ٣٠٩-٣١٠ برج KAFD',
        'category' => 'Industrial',
        'status' => 'completed',
        'location' => 'Riyadh',
        'contract_value' => 'N/A',
        'scope' => 'RCC & MEP with SAUDI BUILD COMPANY',
        'description' => 'Two towers totaling 140,000 m². Tower 309: 20 Floors and 3 Basements. Tower 310: 15 Floors and 3 Basements. Plus Podium 11 Floors with 3 Basements. A landmark project in King Abdullah Financial District.',
        'description_ar' => 'برجين بإجمالي ١٤٠,٠٠٠ م². برج ٣٠٩: ٢٠ طوابق و٣ طوابق سردية. برج ٣١٠: ١٥ طوابق و٣ طوابق سردية. بالإضافة إلى منصة ١١ طوابق مع ٣ طوابق سردية. مشروع معلم في منطقة الملك عبدالله المالية بالرياض.',
        'specs' => [
            'Project Area' => '2 Towers: 140,000 m²',
            'Tower 309' => '20 Floors and 3 Basements',
            'Tower 310' => '15 Floors and 3 Basements',
            'Podium' => '11 Floors with 3 Basements',
            'Location' => 'Riyadh (KAFD)',
            'Partner' => 'SAUDI BUILD COMPANY',
            'Status' => 'Completed',
        ],
        'visible' => '1',
    ],
    'al-wassil-tower' => [
        'title' => 'Al-Wassil Tower Project',
        'title_ar' => 'مشروع برج الواصل',
        'category' => 'Industrial',
        'status' => 'completed',
        'location' => 'King Fahd Road, Riyadh',
        'contract_value' => 'N/A',
        'scope' => 'RCC & MEP with TAROUK CONTRACTING COMPANY',
        'description' => '20 floors covering 20,000 m² plus 5 basements totaling 20,000 m². A prestigious commercial tower on King Fahd Road.',
        'description_ar' => '٢٠ طوابق تغطي ٢٠,٠٠٠ م² بالإضافة إلى ٥ طوابق سردية بإجمالي ٢٠,٠٠٠ م². برج تجاري مشهور على طريق الملك فهد بالرياض.',
        'specs' => [
            'Project Area' => '20 Floors: 20,000 m² + 5 Basements: 20,000 m²',
            'Total Area' => '40,000 m²',
            'Location' => 'King Fahd Road, Riyadh',
            'Partner' => 'TAROUK CONTRACTING COMPANY',
            'Status' => 'Completed',
        ],
        'visible' => '1',
    ],
    'al-swailim-tower' => [
        'title' => 'Al-Swailim Tower Project',
        'title_ar' => 'مشروع برج السويلم',
        'category' => 'Commercial',
        'status' => 'completed',
        'location' => 'Olaya Road, Riyadh',
        'contract_value' => 'N/A',
        'scope' => 'RCC & MEP with TAROUK CONTRACTING COMPANY',
        'description' => '30,000 m² project with 20 floors plus 2 basements and 2 parking floors. A modern commercial tower on Olaya Road.',
        'description_ar' => 'مشروع مساحته ٣٠,٠٠٠ م² مع ٢٠ طوابق بالإضافة إلى ٢ طوابق سردية و٢ طوابق مواقف. برج تجاري حديث على طريق العليا بالرياض.',
        'specs' => [
            'Project Area' => '30,000 m²',
            'Floors' => '20 floors + 2 basements + 2 parking floors',
            'Location' => 'Olaya Road, Riyadh',
            'Partner' => 'TAROUK CONTRACTING COMPANY',
            'Status' => 'Completed',
        ],
        'visible' => '1',
    ],
    'saudi-press-agency' => [
        'title' => 'Saudi Press Agency HQ',
        'title_ar' => 'مشروع مقر الوكالة السعودية للأنباء',
        'category' => 'Commercial',
        'status' => 'completed',
        'location' => 'Riyadh',
        'contract_value' => '12 MM SAR',
        'scope' => 'Civil & MEP',
        'description' => '12,000 sq/m with 10 floors & dome on 4,000 sq/m plot. Client: SPA - Tarouk as main contractor. Consultant: Al Zaid. A prestigious headquarters building completed in 8 months.',
        'description_ar' => '١٢,٠٠٠ م²/م مع ١٠ طوابق وقبة على قطعة أرض مساحتها ٤,٠٠٠ م². العميل: هيئة التحقيق والتحقيق - ترخ كمقاول رئيسي. المستشار: الزيد. مقر مشهور تم إنجازه في ٨ أشهر.',
        'specs' => [
            'Project Area' => '12,000 sq/m (10 floors & Dome)',
            'Plot Area' => '4,000 sq/m',
            'Budget' => '12 Million SAR',
            'Duration' => '8 months',
            'Client' => 'SPA - Tarouk as main contractor',
            'Consultant' => 'Al Zaid',
            'Status' => 'Handed Over',
        ],
        'visible' => '0',
    ],
    'shaqra-roman-theater' => [
        'title' => 'Shaqra Roman Theater',
        'title_ar' => 'مشروع المسرح الروماني في شقرة',
        'category' => 'Commercial',
        'status' => 'in-progress',
        'location' => 'Shaqra',
        'contract_value' => '8 MM SAR',
        'scope' => 'Civil & MEP work',
        'description' => 'Civil & MEP work for Shaqra Roman Theater project.',
        'description_ar' => 'أعمال مدنية وMEP لمشروع المسرح الروماني في شقرة. مشروع معلم ثقافي يحافظ على الهندسة التاريخية مع البنية التحتية الحديثة.',
        'specs' => [
            'Scope of Work' => 'Civil & MEP Work',
            'Contract Value' => '8 Million SAR',
            'Location' => 'Shaqra',
            'Status' => 'ON GOING',
        ],
        'visible' => '0',
    ],
    'al-rimal-showrooms' => [
        'title' => 'Al Rimal Commercial Showrooms',
        'title_ar' => 'مشروع صالات عرض ريمال التجارية',
        'category' => 'Commercial',
        'status' => 'in-progress',
        'location' => 'Riyadh',
        'contract_value' => '8 MM SAR',
        'scope' => 'Earthwork, Civil, MEP, and Finishing Work',
        'description' => 'Comprehensive commercial showrooms project including earthwork, civil construction, MEP systems, and finishing works.',
        'description_ar' => 'مشروع صالات عرض تجارية شامل يشمل أعمال الحفر والبناء المدني وأنظمة MEP وأعمال التشطيب.',
        'specs' => [
            'Scope of Work' => 'Earthwork, Civil, MEP, and Finishing Work',
            'Contract Value' => '8 Million SAR',
            'Location' => 'Riyadh',
            'Status' => 'ON GOING',
        ],
        'visible' => '1',
    ],
    'water-pump-station' => [
        'title' => 'Water Pump House Station Al-Fatiha',
        'title_ar' => 'مشروع محطة ضخ المياه في الفاتحة',
        'category' => 'Infrastructure',
        'status' => 'completed',
        'location' => 'Al-Fatiha, Jazan',
        'contract_value' => '12 MM SAR',
        'scope' => 'Earthwork & Mechanical Work',
        'description' => 'Water pump house station project including earthwork and mechanical work. Critical infrastructure for water distribution in Jazan region.',
        'description_ar' => 'مشروع محطة ضخ المياه يشمل أعمال الحفر والعمل الميكانيكي. بنية تحتية حاسمة لتوزيع المياه في منطقة جازان.',
        'specs' => [
            'Scope of Work' => 'Earthwork & Mechanical Work',
            'Contract Value' => '12 Million SAR',
            'Location' => 'Al-Fatiha, Jazan',
            'Status' => 'Finished',
        ],
        'visible' => '0',
    ],
    'mr-atif-project' => [
        'title' => 'Mr. Atif Bin Ayez Bin Awaz Almezani Almutari',
        'title_ar' => 'السيد عاطف بن عزيز بن عوض المزاني المطري',
        'category' => 'Residential',
        'status' => 'completed',
        'location' => 'Riyadh',
        'contract_value' => '3 MM SAR',
        'scope' => 'Earthwork, Civil & MEP Work',
        'description' => 'Residential project including earthwork, civil construction, and MEP work for private client.',
        'description_ar' => 'مشروع سكني يشمل أعمال الحفر والبناء المدني وأعمال MEP لعميل خاص.',
        'specs' => [
            'Scope of Work' => 'Earthwork, Civil & MEP Work',
            'Contract Value' => '3 Million SAR',
            'Location' => 'Riyadh',
            'Status' => 'Finished',
        ],
        'visible' => '0',
    ],
    'mr-saleh-project' => [
        'title' => 'Mr. Saleh Bin Al-Rasheed Allya',
        'title_ar' => 'السيد صالح بن الرشيد عليا',
        'category' => 'Residential',
        'status' => 'completed',
        'location' => 'Riyadh',
        'contract_value' => '15 MM SAR',
        'scope' => 'CIVIL, FINISHES & MEP WORKS',
        'description' => 'Comprehensive residential project including civil construction, finishing works, and MEP systems.',
        'description_ar' => 'مشروع سكني شامل يشمل البناء المدني وأعمال التشطيب وأنظمة MEP.',
        'specs' => [
            'Scope of Work' => 'CIVIL, FINISHES & MEP WORKS',
            'Contract Value' => '15 Million SAR',
            'Location' => 'Riyadh',
            'Status' => 'Finished',
        ],
        'visible' => '0',
    ],
    'princess-jawaher' => [
        'title' => 'Princess Jawaher Bint Muqrin Bin Abdulaziz Al-Saud',
        'title_ar' => 'الأميرة جواهر بنت مقرين بن عبدالعزيز آل سعود',
        'category' => 'Residential',
        'status' => 'completed',
        'location' => 'Riyadh',
        'contract_value' => '6 MM SAR',
        'scope' => 'CIVIL, FINISHES & MEP WORKS',
        'description' => 'Royal residential project including civil construction, finishing works, and MEP systems with exceptional quality standards.',
        'description_ar' => 'مشروع سكني ملكي يشمل البناء المدني وأعمال التشطيب وأنظمة MEP بمعايير جودة استثنائية.',
        'specs' => [
            'Scope of Work' => 'CIVIL, FINISHES & MEP WORKS',
            'Contract Value' => '6 Million SAR',
            'Location' => 'Riyadh',
            'Status' => 'Finished',
        ],
        'visible' => '0',
    ],
    'nwc-mep' => [
        'title' => 'National Water Company - MEP Works',
        'title_ar' => 'الشركة الوطنية للمياه - أعمال MEP',
        'category' => 'Infrastructure',
        'status' => 'completed',
        'location' => 'Riyadh',
        'contract_value' => '6 MM SAR',
        'scope' => 'MEP WORKS',
        'description' => 'MEP works for National Water Company infrastructure project, ensuring reliable water distribution systems.',
        'description_ar' => 'أعمال MEP للشركة الوطنية للمياه، لتوفير أنظمة توزيع مياه موثوقة.',
        'specs' => [
            'Scope of Work' => 'MEP WORKS',
            'Contract Value' => '6 Million SAR',
            'Location' => 'Riyadh',
            'Status' => 'Finished',
        ],
        'visible' => '0',
    ],
    'nwc-civil-mep' => [
        'title' => 'National Water Company - Civil & MEP',
        'title_ar' => 'الشركة الوطنية للمياه - أعمال مدنية وMEP',
        'category' => 'Infrastructure',
        'status' => 'in-progress',
        'location' => 'Riyadh',
        'contract_value' => '15 MM SAR',
        'scope' => 'Civil & MEP Work',
        'description' => 'Ongoing civil & MEP work for National Water Company, expanding water infrastructure capabilities.',
        'description_ar' => 'أعمال مدنية وMEP جارية للشركة الوطنية للمياه، توسع قدرات البنية التحتية للمياه.',
        'specs' => [
            'Scope of Work' => 'Civil & MEP Work',
            'Contract Value' => '15 Million SAR',
            'Location' => 'Riyadh',
            'Status' => 'ON GOING',
        ],
        'visible' => '0',
    ],
    'riyadh-development' => [
        'title' => 'Arriyadh Development Authority',
        'title_ar' => 'هيئة تطوير الرياض',
        'category' => 'Commercial',
        'status' => 'completed',
        'location' => 'Riyadh',
        'contract_value' => '5.5 MM SAR',
        'scope' => 'MEP & Finishing Work',
        'description' => 'MEP & Finishing work for Arriyadh Development Authority project, supporting urban development initiatives.',
        'description_ar' => 'أعمال MEP والتشطيب لمشروع هيئة تطوير الرياض، لدعم مبادرات التطوير الحضري.',
        'specs' => [
            'Scope of Work' => 'MEP & Finishing Work',
            'Contract Value' => '5.5 Million SAR',
            'Location' => 'Riyadh',
            'Status' => 'Finished',
        ],
        'visible' => '1',
    ],
    'riyadh-metro' => [
        'title' => 'Riyadh Metro Project',
        'title_ar' => 'مشروع مترو الرياض',
        'category' => 'Infrastructure',
        'status' => 'completed',
        'location' => 'Riyadh',
        'contract_value' => '8 MM SAR',
        'scope' => 'Civil & MEP Work',
        'description' => 'Civil & MEP work for the Riyadh Metro Project. Handed over on 10 January 2017. A critical infrastructure project supporting Riyadh\'s public transportation system.',
        'description_ar' => 'أعمال مدنية وMEP لمشروع مترو الرياض. تم التسليم في ١٠ يناير ٢٠١٧. مشروع بنية تحتية حاسمة لدعم نظام النقل العام في الرياض.',
        'specs' => [
            'Scope of Work' => 'Civil & MEP Work',
            'Contract Value' => '8 Million SAR',
            'Location' => 'Riyadh',
            'Handing Over Date' => '10 January 2017',
            'Status' => 'Handed Over',
        ],
        'visible' => '0',
    ],
    'yammam-cement' => [
        'title' => 'Yammam Cement Factory Project',
        'title_ar' => 'مشروع مصنع يمام للإسمنت',
        'category' => 'Industrial',
        'status' => 'completed',
        'location' => 'Yammam',
        'contract_value' => '8 MM SAR',
        'scope' => 'MEP',
        'description' => 'MEP work for Yammam Cement Factory. Handed over on 10 January 2017. Industrial MEP systems for cement production facility.',
        'description_ar' => 'أعمال MEP لمصنع يمام للإسمنت. تم التسليم في ١٠ يناير ٢٠١٧. أنظمة MEP صناعية لمنشأة إنتاج الإسمنت.',
        'specs' => [
            'Scope of Work' => 'MEP',
            'Contract Value' => '8 Million SAR',
            'Location' => 'Yammam',
            'Handing Over Date' => '10 January 2017',
            'Status' => 'Handed Over',
        ],
        'visible' => '0',
    ],
    'salboukh-station' => [
        'title' => 'SSEM-NWC-Salboukh Station',
        'title_ar' => 'محطة صلبوخ SSEM-NWC',
        'category' => 'Infrastructure',
        'status' => 'completed',
        'location' => 'Salboukh',
        'contract_value' => '6.5 MM SAR',
        'scope' => 'Structural, Mechanical and Finishing',
        'description' => 'Structural, Mechanical and Finishing work for Salboukh station. Water infrastructure project in Salboukh region.',
        'description_ar' => 'أعمال إنشائية وميكانيكية وتشطيب لمحطة صلبوخ. مشروع بنية تحتية للمياه في منطقة صلبوخ.',
        'specs' => [
            'Scope of Work' => 'Structural, Mechanical and Finishing',
            'Contract Value' => '6.5 Million SAR',
            'Location' => 'Salboukh',
            'Status' => 'Completed',
        ],
        'visible' => '0',
    ],
    'california-compound' => [
        'title' => 'California Compound',
        'title_ar' => 'مشروع مجمع كاليفورنيا',
        'category' => 'Residential',
        'status' => 'completed',
        'location' => 'Riyadh - Exit 7',
        'contract_value' => '33 MM SAR',
        'scope' => 'Civil & MEP',
        'description' => 'Large-scale residential compound project including comprehensive civil & MEP work. A major residential development in Riyadh.',
        'description_ar' => 'مشروع مجمع سكني كبير يشمل أعمال مدنية وMEP شاملة. مشروع سكني رئيسي في الرياض.',
        'specs' => [
            'Scope of Work' => 'Civil & MEP',
            'Contract Value' => '33 Million SAR',
            'Location' => 'Riyadh - Exit 7',
            'Status' => 'Completed',
        ],
        'visible' => '1',
    ],
    'al-rashed-palace' => [
        'title' => 'Al Rashed Palace',
        'title_ar' => 'قصر الراشد',
        'category' => 'Residential',
        'status' => 'completed',
        'location' => 'Riyadh Exit #2',
        'contract_value' => '10 MM SAR',
        'scope' => 'MEP',
        'description' => 'MEP work for Al Rashed Palace. Prestigious residential project with comprehensive mechanical, electrical, and plumbing systems.',
        'description_ar' => 'أعمال MEP لقصر الراشد. مشروع سكني مشهور مع أنظمة ميكانيكية وكهربائية وأنظمة سباكة شاملة.',
        'specs' => [
            'Scope of Work' => 'MEP',
            'Contract Value' => '10 Million SAR',
            'Location' => 'Riyadh Exit #2',
            'Status' => 'Completed',
        ],
        'visible' => '1',
    ],
    'ballan-tower' => [
        'title' => 'Ballan Commercial Tower',
        'title_ar' => 'برج بالان التجاري',
        'category' => 'Commercial',
        'status' => 'completed',
        'location' => 'Riyadh',
        'contract_value' => '6 MM SAR',
        'scope' => 'MEP',
        'description' => 'MEP work for Ballan Commercial Tower. Structural work 8,000 sq/m. Modern commercial tower with advanced MEP systems.',
        'description_ar' => 'أعمال MEP لبرج بالان التجاري. عمل إنشائي مساحته ٨,٠٠٠ م². برج تجاري حديث بأنظمة MEP متقدمة.',
        'specs' => [
            'Scope of Work' => 'MEP',
            'Structural Work' => '8,000 sq/m',
            'Contract Value' => '6 Million SAR',
            'Location' => 'Riyadh',
            'Status' => 'Completed',
        ],
        'visible' => '1',
    ],
    'king-fahd-stadium' => [
        'title' => 'King Fahd Stadium Project',
        'title_ar' => 'مشروع استاد الملك فهد',
        'category' => 'Infrastructure',
        'status' => 'completed',
        'location' => 'Riyadh',
        'contract_value' => '25 MM SAR',
        'scope' => 'Civil, MEP & Finishing',
        'description' => 'Comprehensive stadium project including civil construction, MEP systems, and finishing works. A major sports infrastructure development.',
        'description_ar' => 'مشروع استاد شامل يشمل البناء المدني وأنظمة MEP وأعمال التشطيب. مشروع بنية تحتية رياضية رئيسي.',
        'specs' => [
            'Scope of Work' => 'Civil, MEP & Finishing Works',
            'Project Type' => 'Sports Stadium Infrastructure',
            'Contract Value' => '25 Million SAR',
            'Location' => 'Riyadh',
            'Status' => 'Completed',
        ],
        'visible' => '0',
    ],
];

?>